version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                # Root directory; change if your package.json is elsewhere
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5   # Optional: limit open PRs
    labels:
      - "dependencies"
      - "dependabot"
    assignees:
      - "krema"
