name: Unit Test

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install pnpm
      run: npm install -g pnpm@10

    - name: ⤵️ Check out code from GitHub
      uses: actions/checkout@v3

    - name: 🏗 Setup node version
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'pnpm'

    - name: 🏗 Install dependencies
      run: pnpm install --frozen-lockfile

    - name: 🏗 Build Library
      run: pnpm build --if-present

    - name: 🧪 Run tests
      run: |
           pnpm test
           pnpm lint
           pnpm format:check
